class UsersController < ApplicationController

  before_action :signed_in_user,      only: [:index, :edit, :update, :destroy]
  before_action :correct_user,        only: [:edit, :update]
  before_action :admin_user,          only: :destroy
  before_action :redirect_signed_in,  only: [ :new, :create ]


  def index
    @users = User.paginate(page: params[:page]) # params[:page] - parameter generated by will_paginate on view
  end


  def new
    @user = User.new
  end


  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end


  def show
    @user = User.find(params[:id])
  end


  def edit
    # Next line no more needed, commented out, due to @user variable is defined in
    # correct_user method called right before edit action is fired (see before_action on the top)
    #@user = User.find(params[:id])
  end


  def update
    # Next line no more needed, commented out, due to @user variable is defined in
    # correct_user method called right before edit action is fired (see before_action on the top)
    #@user = User.find(params[:id])

    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      render 'edit'
    end
  end


  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end


  private

    def user_params
      params.require(:user).permit(
        :name,
        :email,
        :password,
        :password_confirmation
      )
    end


    # Before filters

    # If there is no user signed in, this method redirects to sign-in page
    # while it also stores the requested url location.
    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in." 
        # NOTE: notice: "Please sign in." is a shortcut parameter of redirect_to.
        # It could be 
        #  flash[:notice] = "Please sign in."
        #  redirect_to signin_url
        # too.
      end
    end


    # Redirects to root unless user with id specified in request's params is the one 
    # currently signed in.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end


    # Redirects to root unless user currently logged in is an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end


    def redirect_signed_in
      if signed_in?
        redirect_to root_url
      end
    end
  
end
